# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.base_model_ import Model
from swagger_server import util


class TradeStrategyConfigRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self,
        mode: str = None,
    ):  # noqa: E501
        """TradeStrategyConfigRequest - a model defined in Swagger

        :param mode: The mode of this TradeStrategyConfigRequest.
        :type mode: string
        """

        self.swagger_types = {
            'mode': str
        }

        self.attribute_map = {
            'mode': 'mode'
        }

        self._mode = mode

    @classmethod
    def from_dict(cls, dikt) -> 'TradeStrategyConfigRequest':
        """Returns the dict as a model"""
        return util.deserialize_model(dikt, cls)

    # ---- Property definitions ----
    @property
    def mode(self) -> str:
        return self._mode

    @mode.setter
    def mode(self, mode: str):
        self._mode = mode